### ISSUE TITLE
File error: Bad input file ./data/chembl31.smi

### ISSUE THREAD

**Issue by ljh433** [ecust-hc/ScaffoldGVAE#2]
Thank you for your outstanding work！When I run python Sca_extraction.py , I am prompted with the following error：
Traceback (most recent call last):
  File "Sca_extraction.py", line 99, in <module>
    main(args)
  File "Sca_extraction.py", line 53, in main
    network = sg.ScaffoldNetwork.from_smiles_file(args.data)
  File "/sda/liangjh/software/Anaconda3/envs/ScaffoldGVAE/lib/python3.6/site-packages/scaffoldgraph/core/graph.py", line 881, in from_smiles_file
    header, requires_length=progress is True
  File "/sda/liangjh/software/Anaconda3/envs/ScaffoldGVAE/lib/python3.6/site-packages/scaffoldgraph/io/smiles.py", line 47, in read_smiles_file
    True))
OSError: File error: Bad input file ./data/chembl31.smi

could you provide and upload this file？

**Comment by ecust-hc** [comment]
Hello, may I ask if you have created the data directory and put the data in this directory
